# Generated by Django 4.0.4 on 2022-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='actors/')),
                ('full_name', models.CharField(max_length=50, null=True)),
                ('biography', models.TextField()),
                ('birthday', models.DateField()),
                ('role', models.CharField(choices=[('a', 'Actor'), ('d', 'Director')], default='a', max_length=1)),
                ('token', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
