# Generated by Django 4.0.4 on 2022-09-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='Movie-images')),
                ('name', models.CharField(max_length=20)),
                ('intro', models.TextField()),
                ('imdb', models.PositiveIntegerField(default=0)),
                ('release_date', models.DateField()),
                ('token', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('actors', models.ManyToManyField(blank=True, related_name='movie_actor', to='element.element')),
                ('director', models.ManyToManyField(blank=True, related_name='movie_director', to='element.element')),
                ('genre', models.ManyToManyField(blank=True, related_name='movie_genre', to='element.genre')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(default=1)),
                ('story', models.TextField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=10)),
                ('for_film', models.ManyToManyField(blank=True, related_name='seasons', to='movie.film')),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='views',
            field=models.ManyToManyField(blank=True, to='movie.view'),
        ),
    ]
