# Generated by Django 3.2.13 on 2022-05-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20220508_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='seoson_story',
            field=models.ManyToManyField(blank=True, to='movie.seoson'),
        ),
    ]
