# Generated by Django 4.0.4 on 2022-10-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_for_film_season_film_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='film',
        ),
        migrations.AddField(
            model_name='season',
            name='film',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='movie.film'),
            preserve_default=False,
        ),
    ]
