# Generated by Django 3.2.13 on 2022-05-08 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_film_seoson_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='seoson',
            name='story',
            field=models.TextField(blank=True, null=True),
        ),
    ]
