# Generated by Django 3.2.13 on 2022-05-08 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='actors/')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('biography', models.TextField()),
                ('birthday', models.DateField()),
                ('role', models.CharField(choices=[('a', 'Actor'), ('d', 'Director')], default='a', max_length=1)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.genre')),
            ],
        ),
    ]
