# Generated by Django 3.2.13 on 2022-05-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='genre',
        ),
        migrations.AddField(
            model_name='cast',
            name='genre',
            field=models.ManyToManyField(to='cast.Genre'),
        ),
    ]
