# Generated by Django 3.2.13 on 2022-05-08 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
        ('cast', '0002_auto_20220508_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='cast',
            name='works',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.film'),
        ),
        migrations.AddField(
            model_name='genre',
            name='films_related',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='movie.film'),
        ),
    ]
