# Generated by Django 3.2.13 on 2022-05-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0003_auto_20220508_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cast',
            name='genre',
            field=models.ManyToManyField(blank=True, to='cast.Genre'),
        ),
    ]
