# Generated by Django 3.2.13 on 2022-05-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cast', '0004_alter_cast_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cast',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='cast',
            name='last_name',
        ),
        migrations.AddField(
            model_name='cast',
            name='full_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
